### ISSUE TITLE
Method that returns a collection of an inner class is ignored

### ISSUE THREAD

**Issue by pablopioli** [giacomelli/DocsByReflection#11]
I found an edge case that it's not handled. 

> 
> class outerclass
> {
>    void SomeFunction(innerclass[] input)
>    {}
> 
>    class innerclass
>    {}
> }
> 

In this case SomeFunction is ignored and the library cannot find the documentation for the element.

I added support for this case, it's really simple. In DocsTypeService add 

>             else if (type.IsNested)
>             {
>                 return String.Format(CultureInfo.InvariantCulture, "{0}{1}.{2}{3}", typeNamespace, type.DeclaringType.Name, type.Name, isOut ? "@" : "").Replace("&", "");
>             }
>             else if (type.GetElementType() != null && type.GetElementType().IsNested)
>             { // this is new
>                 return String.Format(CultureInfo.InvariantCulture, "{0}{1}.{2}{3}", typeNamespace, type.GetElementType().DeclaringType.Name, type.Name, isOut ? "@" : "").Replace("&", "");
>             }
>             else
>             {
>                 return String.Format(CultureInfo.InvariantCulture, "{0}{1}{2}", typeNamespace, type.Name, isOut ? "@" : "").Replace("&", "");
>             }
> 

Are the maintainer interested in adding this case?
Anyway, hope this modification helps someone.

**Comment by giacomelli** [comment]
Yes, we could added it to the library. @pablopioli could you please make a pull-request with this change?

Would be great if you add a test for this in the [DocsServiceTest.cs](https://github.com/giacomelli/DocsByReflection/blob/master/DocsByReflection.UnitTests/DocsServiceTest.cs).

Thanks!

**Comment by giacomelli** [comment]
Closed by #12
