### ISSUE TITLE
Exception getting documentation when exist comment in xml file

### ISSUE THREAD

**Issue by jlvazcla** [giacomelli/DocsByReflection#3]
Hello,

When in xml file exist a comment an InvalidCastException is thrown: "Unable to cast object of type 'System.Xml.XmlComment' to type 'System.Xml.XmlElement'."

You can se this exception by example using Microsoft.Data.Service.xml in 
        
        <member name="T:System.Data.Services.IProjectedResult">
            <summary>

            This interface declares the methods required to support getting values
            from projected results for $select queries
            </summary>

        </member>

I found the exception is thrown in the public static method GetXmlFromName in DocsTypeService.cs. In the foreach loop over the xmlDocument["doc"]["members"].

Regards,

José Luis

**Comment by josephadams-izenda** [comment]
I am getting the same exception. I will look for a way to fix this. I have forked the repository, so I could submit my fix for review as well.

**Comment by giacomelli** [comment]
@josephadams-izenda have you fixed this issue on your DocsByReflection fork?

**Comment by josephadams-izenda** [comment]
I honestly forgot all about this.
